#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Aptoria private license issuer.
 *
 * This tool is meant for the license issuer's private machine/repository.
 * It reads an Aptoria license request JSON, builds a license payload, signs it
 * with an RSA private key using SHA-256 and writes aptoria-license.json.
 *
 * The private key must never be committed or shipped to customers.
 */

function fail(string $message, int $code = 1): never
{
    fwrite(STDERR, "ERROR: {$message}\n");
    exit($code);
}

function info(string $message): void
{
    fwrite(STDOUT, $message."\n");
}

function usage(): void
{
    info(<<<'TXT'
Aptoria License Issuer

Usage:
  php issue-license.php --request=license-request.json --private-key=private.pem --output=aptoria-license.json [options]

Required:
  --request=PATH        Aptoria license request JSON generated by the runtime
  --private-key=PATH    RSA private key PEM used for signing
  --output=PATH         Output aptoria-license.json path

Common options:
  --license-id=ID       License ID. Default: generated APT-YYYYMMDD-XXXXXX
  --subject=TEXT        Customer/deployment label. Default: Aptoria Customer
  --issued-to=TEXT      Optional email/account label
  --edition=NAME        portable, server, trial, internal. Default: portable
  --expires=DATE        Expiry date/time. Default: +1 year UTC
  --binding=MODE        machine, usb, machine_or_usb, none. Default: machine_or_usb
  --features=CSV        Comma-separated feature list
  --max-users=N         Optional maximum users metadata
  --notes=TEXT          Optional license note
  --issuer=TEXT         Optional issuer label. Default: Aptoria License Issuer
  --force               Allow overwriting output file

Examples:
  php issue-license.php --request=license-request.json --private-key=keys/private.pem --output=aptoria-license.json --subject="Customer Demo" --expires=2027-06-20 --binding=machine_or_usb
  php issue-license.php --request=license-request.json --private-key=keys/private.pem --output=aptoria-license.json --edition=server --binding=machine --features=evidence_repository,release_gate,client_portal
TXT);
}

$options = getopt('', [
    'request:',
    'private-key:',
    'output:',
    'license-id::',
    'subject::',
    'issued-to::',
    'edition::',
    'expires::',
    'binding::',
    'features::',
    'max-users::',
    'notes::',
    'issuer::',
    'force',
    'help',
]);

if (isset($options['help'])) {
    usage();
    exit(0);
}

foreach (['request', 'private-key', 'output'] as $required) {
    if (! isset($options[$required]) || trim((string) $options[$required]) === '') {
        usage();
        fail("Missing required --{$required} option.");
    }
}

$requestPath = absolutePath((string) $options['request']);
$privateKeyPath = absolutePath((string) $options['private-key']);
$outputPath = absolutePath((string) $options['output']);

if (! is_file($requestPath)) {
    fail("Request file not found: {$requestPath}");
}

if (! is_file($privateKeyPath)) {
    fail("Private key file not found: {$privateKeyPath}");
}

if (is_file($outputPath) && ! isset($options['force'])) {
    fail("Output already exists. Use --force to overwrite: {$outputPath}");
}

$request = decodeJsonFile($requestPath, 'license request');
validateRequest($request);

$privateKey = file_get_contents($privateKeyPath);
if (! is_string($privateKey) || trim($privateKey) === '') {
    fail('Private key file is empty.');
}

$privateKeyResource = openssl_pkey_get_private($privateKey);
if ($privateKeyResource === false) {
    fail('Private key is not a readable RSA private key.');
}

$bindingMode = (string) ($options['binding'] ?? 'machine_or_usb');
if (! in_array($bindingMode, ['none', 'machine', 'usb', 'machine_or_usb'], true)) {
    fail('Invalid binding mode. Use: none, machine, usb, machine_or_usb.');
}

$features = parseFeatures((string) ($options['features'] ?? 'portable_usb,evidence_repository,import_adapter,native_test_evidence,release_gate,client_portal'));
$licenseId = trim((string) ($options['license-id'] ?? '')) ?: generatedLicenseId();
$subject = trim((string) ($options['subject'] ?? '')) ?: 'Aptoria Customer';
$issuedTo = trim((string) ($options['issued-to'] ?? ''));
$edition = trim((string) ($options['edition'] ?? 'portable')) ?: 'portable';
$issuer = trim((string) ($options['issuer'] ?? 'Aptoria License Issuer'));
$expiresAt = normalizeExpiry((string) ($options['expires'] ?? '+1 year'));
$issuedAt = gmdate('Y-m-d\TH:i:s\Z');
$fingerprints = fingerprintsForMode($request, $bindingMode);

$payload = array_filter([
    'license_id' => $licenseId,
    'product' => 'aptoria',
    'edition' => $edition,
    'subject' => $subject,
    'issued_to' => $issuedTo !== '' ? $issuedTo : null,
    'issued_at' => $issuedAt,
    'expires_at' => $expiresAt,
    'max_users' => isset($options['max-users']) && trim((string) $options['max-users']) !== '' ? max(1, (int) $options['max-users']) : null,
    'features' => array_values($features),
    'fingerprint_binding' => [
        'mode' => $bindingMode,
        'fingerprints' => array_values($fingerprints),
    ],
    'issuer' => $issuer,
    'source_request' => [
        'request_id' => $request['request_id'] ?? null,
        'request_format' => $request['request_format'] ?? null,
        'version' => $request['version'] ?? null,
        'generated_at' => $request['generated_at'] ?? null,
    ],
    'notes' => trim((string) ($options['notes'] ?? '')) ?: null,
], static fn ($value): bool => $value !== null && $value !== '');

$canonical = canonicalPayload($payload);
$signature = '';
if (! openssl_sign($canonical, $signature, $privateKeyResource, OPENSSL_ALGO_SHA256)) {
    fail('Unable to sign payload with the supplied private key.');
}

$document = [
    'payload' => $payload,
    'signature' => base64_encode($signature),
];

$encoded = json_encode($document, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
if (! is_string($encoded)) {
    fail('Unable to encode license JSON.');
}

$directory = dirname($outputPath);
if (! is_dir($directory) && ! mkdir($directory, 0775, true) && ! is_dir($directory)) {
    fail("Unable to create output directory: {$directory}");
}

file_put_contents($outputPath, $encoded."\n");

info('License written to: '.$outputPath);
info('License ID: '.$licenseId);
info('Subject: '.$subject);
info('Edition: '.$edition);
info('Expires at: '.$expiresAt);
info('Binding mode: '.$bindingMode);
info('Fingerprints: '.count($fingerprints));
info('Features: '.implode(', ', $features));

function absolutePath(string $path): string
{
    $path = trim($path);
    if ($path === '') {
        return $path;
    }

    if (preg_match('/^[A-Z]:[\\\\\/]/i', $path) || str_starts_with($path, '/')) {
        return $path;
    }

    return getcwd().DIRECTORY_SEPARATOR.$path;
}

function decodeJsonFile(string $path, string $label): array
{
    $raw = file_get_contents($path);
    if (! is_string($raw)) {
        fail("Unable to read {$label}: {$path}");
    }

    try {
        $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException $exception) {
        fail("Invalid {$label} JSON: ".$exception->getMessage());
    }

    if (! is_array($decoded)) {
        fail("{$label} must decode to a JSON object.");
    }

    return $decoded;
}

function validateRequest(array $request): void
{
    if (($request['product'] ?? null) !== 'aptoria') {
        fail('License request product must be aptoria.');
    }

    if (! is_array($request['fingerprints'] ?? null)) {
        fail('License request is missing fingerprints.');
    }
}

function parseFeatures(string $features): array
{
    $items = array_filter(array_map(static fn (string $item): string => trim($item), explode(',', $features)));

    return $items === [] ? ['portable_usb'] : array_values(array_unique($items));
}

function generatedLicenseId(): string
{
    return 'APT-'.gmdate('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
}

function normalizeExpiry(string $value): string
{
    $value = trim($value);
    if ($value === '') {
        $value = '+1 year';
    }

    $timestamp = strtotime($value);
    if ($timestamp === false) {
        fail('Invalid --expires value. Use YYYY-MM-DD, ISO-8601 or relative value such as +1 year.');
    }

    if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $value)) {
        return gmdate('Y-m-d\T23:59:59\Z', $timestamp);
    }

    return gmdate('Y-m-d\TH:i:s\Z', $timestamp);
}

function fingerprintsForMode(array $request, string $mode): array
{
    if ($mode === 'none') {
        return [];
    }

    $machine = normalizeFingerprint((string) ($request['fingerprints']['machine'] ?? ''));
    $usb = normalizeFingerprint((string) ($request['fingerprints']['usb'] ?? ''));
    $fingerprints = [];

    if (($mode === 'machine' || $mode === 'machine_or_usb') && $machine !== null) {
        $fingerprints[] = $machine;
    }

    if (($mode === 'usb' || $mode === 'machine_or_usb') && $usb !== null) {
        $fingerprints[] = $usb;
    }

    if ($fingerprints === []) {
        fail("Binding mode {$mode} requires a matching fingerprint in the license request.");
    }

    return array_values(array_unique($fingerprints));
}

function normalizeFingerprint(string $fingerprint): ?string
{
    $fingerprint = trim(strtolower($fingerprint));
    if ($fingerprint === '') {
        return null;
    }

    return str_starts_with($fingerprint, 'sha256:') ? $fingerprint : 'sha256:'.$fingerprint;
}

function canonicalPayload(array $payload): string
{
    $normalized = sortRecursive($payload);

    return json_encode($normalized, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION) ?: '{}';
}

function sortRecursive(array $value): array
{
    foreach ($value as $key => $item) {
        if (is_array($item)) {
            $value[$key] = sortRecursive($item);
        }
    }

    ksort($value);

    return $value;
}
