@extends('layouts.app')
@section('title', __('messages.evidence_packs.title'))
@section('page_title', __('messages.evidence_packs.title'))
@section('page_actions')
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#evidencePackCreateModal"><i data-lucide="archive" class="me-1"></i>{{ __('messages.evidence_packs.new') }}</button>
@endsection
@section('content')
<div class="row g-3 mb-3">
    <div class="col-xl-8"><div class="card aptoria-panel-card"><div class="card-body"><span class="badge badge-soft-primary badge-label mb-2"><i class="ti ti-point-filled"></i>{{ __('messages.evidence_packs.export_center') }}</span><h2 class="fw-normal mb-2">{{ __('messages.evidence_packs.heading') }}</h2><p class="text-muted mb-0">{{ __('messages.evidence_packs.copy') }}</p></div><div class="card-footer aptoria-card-footer-subtle text-muted">{{ __('messages.evidence_packs.footer') }}</div></div></div>
    <div class="col-xl-4"><div class="card aptoria-panel-card"><div class="card-body d-flex align-items-center gap-3"><span class="avatar avatar-md rounded text-bg-primary"><span class="avatar-title"><i data-lucide="archive"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.evidence_packs.total') }}</p><h3 class="fw-light mb-0">{{ $packs->count() }}</h3></div></div></div></div>
</div>
<div class="card aptoria-table-card aptoria-panel-card">
    <div class="card-header border-light justify-content-between align-items-center"><div><h5 class="card-title mb-1"><i data-lucide="archive" class="me-2"></i>{{ __('messages.evidence_packs.table_title') }}</h5><p class="text-muted small mb-0">{{ __('messages.evidence_packs.table_copy') }}</p></div><span class="badge badge-soft-primary">{{ $packs->count() }}</span></div>
    <div class="card-body p-0"><div class="table-responsive"><table data-tables="evidence-packs" class="table table-custom table-striped table-nowrap table-centered mb-0 w-100 aptoria-resource-table"><thead><tr><th>{{ __('messages.evidence_packs.pack') }}</th><th>{{ __('messages.evidence_packs.type') }}</th><th>{{ __('messages.evidence_packs.sections') }}</th><th>{{ __('messages.evidence_packs.checksum') }}</th><th>{{ __('messages.common.created') }}</th><th class="text-end aptoria-actions-cell">{{ __('messages.common.actions') }}</th></tr></thead><tbody>
        @forelse($packs as $pack)
            <tr><td><a href="{{ route('projects.evidence-packs.show', [$project, $pack]) }}" class="fw-medium text-body">{{ $pack->title }}</a><small class="text-muted d-block">{{ $pack->createdBy?->name ?? '—' }}</small></td><td><span class="badge badge-soft-primary badge-label"><i class="ti ti-point-filled"></i>{{ $pack->pack_type_label }}</span></td><td><span class="text-muted">{{ implode(', ', $pack->included_sections_json ?? []) }}</span></td><td><code>{{ Str::limit($pack->checksum, 14, '') }}</code></td><td><small class="text-muted">{{ $pack->generated_at?->format('Y-m-d H:i') }}</small></td><td class="text-end aptoria-actions-cell"><div class="dropdown"><button class="btn btn-light btn-icon btn-sm rounded-circle" data-bs-toggle="dropdown"><i class="ti ti-dots"></i></button><div class="dropdown-menu dropdown-menu-end"><a href="{{ route('projects.evidence-packs.show', [$project, $pack]) }}" class="dropdown-item"><i data-lucide="eye" class="me-2"></i>{{ __('messages.common.open') }}</a><a href="{{ route('projects.evidence-packs.download', [$project, $pack, 'html']) }}" class="dropdown-item"><i data-lucide="code-xml" class="me-2"></i>HTML</a><a href="{{ route('projects.evidence-packs.download', [$project, $pack, 'pdf']) }}" class="dropdown-item"><i data-lucide="file-badge" class="me-2"></i>PDF</a><a href="{{ route('projects.evidence-packs.download', [$project, $pack, 'zip']) }}" class="dropdown-item"><i data-lucide="archive" class="me-2"></i>ZIP</a><a href="{{ route('projects.evidence-packs.download', [$project, $pack, 'md']) }}" class="dropdown-item"><i data-lucide="file-pen-line" class="me-2"></i>Markdown</a><a href="{{ route('projects.evidence-packs.download', [$project, $pack, 'json']) }}" class="dropdown-item"><i data-lucide="braces" class="me-2"></i>JSON</a></div></div></td></tr>
        @empty
            <tr><td colspan="6" class="text-center text-muted py-5">{{ __('messages.evidence_packs.empty') }}</td></tr>
        @endforelse
    </tbody></table></div></div>
</div>

<div class="modal fade" id="evidencePackCreateModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form method="POST" action="{{ route('projects.evidence-packs.store', $project) }}" class="modal-content" data-aptoria-form-plugin>@csrf<div class="modal-header"><h5 class="modal-title"><i data-lucide="archive" class="me-2"></i>{{ __('messages.evidence_packs.new') }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">{{ __('messages.evidence_packs.pack_title') }}</label><input name="title" class="form-control" required placeholder="{{ __('messages.evidence_packs.title_placeholder') }}"></div><div class="col-md-4"><label class="form-label">{{ __('messages.evidence_packs.type') }}</label><select name="pack_type" class="form-select">@foreach(\App\Models\EvidencePack::TYPES as $type)<option value="{{ $type }}">{{ __('messages.evidence_packs.types.'.$type) }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">{{ __('messages.nav.release_readiness') }}</label><select name="release_readiness_run_id" class="form-select"><option value="">{{ __('messages.evidence_packs.latest_readiness') }}</option>@foreach($readinessRuns as $run)<option value="{{ $run->id }}">#{{ $run->id }} · {{ $run->status }} · {{ $run->generated_at?->format('Y-m-d H:i') }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">{{ __('messages.nav.reports') }}</label><select name="report_version_id" class="form-select"><option value="">{{ __('messages.evidence_packs.latest_report') }}</option>@foreach($reportVersions as $report)<option value="{{ $report->id }}">#{{ $report->id }} · {{ $report->title }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">{{ __('messages.evidence_packs.sections') }}</label><div class="row g-2">@foreach(\App\Models\EvidencePack::SECTIONS as $section)<div class="col-md-4"><label class="border rounded p-2 d-flex gap-2 align-items-center"><input type="checkbox" name="sections[]" value="{{ $section }}" @checked(in_array($section, ['readiness','findings','evidence','manifest']))> <span>{{ __('messages.evidence_packs.sections_list.'.$section) }}</span></label></div>@endforeach</div><div class="form-text">{{ __('messages.evidence_packs.sections_help') }}</div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('messages.common.cancel') }}</button><button class="btn btn-primary"><i data-lucide="archive" class="me-1"></i>{{ __('messages.evidence_packs.generate') }}</button></div></form></div></div>
@endsection
