<?php

namespace App\Services\Reports;

use App\Models\Project;
use App\Services\Exports\ExportCreditService;

class ReportPresentationService
{
    public function __construct(private readonly ExportCreditService $credits)
    {
    }

    public function htmlFromMarkdown(string $markdown, string $title, ?Project $project = null): string
    {
        $body = $this->markdownToHtml($markdown);
        $credit = $this->credits->shortLine();
        $logo = $this->embeddedLogo();
        $safeTitle = e($title);
        $projectLine = $project ? '<span>Project: '.e($project->name).'</span>' : '';

        return '<!doctype html>' . "\n"
            . '<html lang="en">' . "\n"
            . '<head>' . "\n"
            . '<meta charset="utf-8">' . "\n"
            . '<meta name="viewport" content="width=device-width, initial-scale=1">' . "\n"
            . '<title>'.$safeTitle.'</title>' . "\n"
            . '<style>' . $this->htmlCss() . '</style>' . "\n"
            . '</head>' . "\n"
            . '<body>' . "\n"
            . '<div class="report-shell">' . "\n"
            . '<header class="report-cover">' . "\n"
            . '<div class="brand">'.$logo.'<div><strong>Aptoria</strong><span>Self-hosted API QA, security review and regression monitoring</span></div></div>' . "\n"
            . '<div class="meta">'.$projectLine.'<span>Version: '.e((string) config('aptoria.version')).'</span><span>Generated: '.e(now()->format('Y-m-d H:i:s')).'</span></div>' . "\n"
            . '</header>' . "\n"
            . '<main class="report-content">' . "\n"
            . $body . "\n"
            . '</main>' . "\n"
            . '<footer class="report-footer">'.e($credit !== '' ? $credit : 'Generated by Aptoria v'.config('aptoria.version')).'</footer>' . "\n"
            . '</div>' . "\n"
            . '</body>' . "\n"
            . '</html>' . "\n";
    }

    public function pdfFromMarkdown(string $markdown, string $title, ?Project $project = null): string
    {
        $renderer = new SimplePdfReportRenderer(
            (string) config('aptoria.product_name', 'Aptoria'),
            (string) config('aptoria.version'),
            $this->credits->shortLine()
        );

        return $renderer->render($markdown, $title, $project?->name);
    }

    private function markdownToHtml(string $markdown): string
    {
        $lines = preg_split('/\r\n|\r|\n/', $markdown) ?: [];
        $html = [];
        $paragraph = [];
        $listOpen = false;
        $table = [];

        $flushParagraph = function () use (&$html, &$paragraph): void {
            if ($paragraph === []) {
                return;
            }
            $html[] = '<p>'.$this->inline(implode(' ', $paragraph)).'</p>';
            $paragraph = [];
        };
        $closeList = function () use (&$html, &$listOpen): void {
            if ($listOpen) {
                $html[] = '</ul>';
                $listOpen = false;
            }
        };
        $flushTable = function () use (&$html, &$table): void {
            if ($table === []) {
                return;
            }
            $html[] = '<table>';
            foreach ($table as $index => $row) {
                $tag = $index === 0 ? 'th' : 'td';
                $html[] = '<tr>'.implode('', array_map(fn (string $cell): string => '<'.$tag.'>'.$this->inline(trim($cell)).'</'.$tag.'>', $row)).'</tr>';
            }
            $html[] = '</table>';
            $table = [];
        };

        foreach ($lines as $line) {
            $raw = rtrim((string) $line);
            $trimmed = trim($raw);

            if ($trimmed === '') {
                $flushParagraph();
                $flushTable();
                $closeList();
                continue;
            }

            if (preg_match('/^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/', $trimmed)) {
                continue;
            }

            if (str_starts_with($trimmed, '|') && str_ends_with($trimmed, '|')) {
                $flushParagraph();
                $closeList();
                $cells = array_map('trim', explode('|', trim($trimmed, '|')));
                $table[] = $cells;
                continue;
            }

            $flushTable();

            if (preg_match('/^(#{1,4})\s+(.*)$/', $trimmed, $match)) {
                $flushParagraph();
                $closeList();
                $level = min(4, strlen($match[1]));
                $html[] = '<h'.$level.'>'.$this->inline($match[2]).'</h'.$level.'>';
                continue;
            }

            if ($trimmed === '---') {
                $flushParagraph();
                $closeList();
                $html[] = '<hr>';
                continue;
            }

            if (preg_match('/^-\s+(.*)$/', $trimmed, $match)) {
                $flushParagraph();
                if (! $listOpen) {
                    $html[] = '<ul>';
                    $listOpen = true;
                }
                $html[] = '<li>'.$this->inline($match[1]).'</li>';
                continue;
            }

            $paragraph[] = $trimmed;
        }

        $flushParagraph();
        $flushTable();
        $closeList();

        return implode("\n", $html);
    }

    private function inline(string $text): string
    {
        $text = e($text);
        $text = preg_replace('/`([^`]+)`/', '<code>$1</code>', $text) ?? $text;
        $text = preg_replace('/\*\*([^*]+)\*\*/', '<strong>$1</strong>', $text) ?? $text;
        $text = preg_replace('/_([^_]+)_/', '<em>$1</em>', $text) ?? $text;

        return $text;
    }

    private function embeddedLogo(): string
    {
        $path = public_path('assets/aptoria/img/aptoria-logo-horizontal.png');
        if (is_file($path)) {
            $data = base64_encode((string) file_get_contents($path));
            return '<img src="data:image/png;base64,'.$data.'" alt="Aptoria" class="logo">';
        }

        return '<div class="logo-fallback">A</div>';
    }

    private function htmlCss(): string
    {
        return <<<'CSS'
:root{--ink:#172033;--muted:#64748b;--line:#e2e8f0;--panel:#f8fafc;--brand:#0f766e;--brand2:#2563eb;}
*{box-sizing:border-box}body{margin:0;background:#eef2f7;color:var(--ink);font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.55}.report-shell{max-width:1080px;margin:32px auto;background:#fff;border:1px solid var(--line);box-shadow:0 18px 50px rgba(15,23,42,.12)}.report-cover{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:26px 34px;border-bottom:1px solid var(--line);background:linear-gradient(135deg,#f8fafc,#eef7ff)}.brand{display:flex;align-items:center;gap:18px}.brand strong{display:block;font-size:26px;letter-spacing:.03em}.brand span,.meta span{display:block;color:var(--muted);font-size:12px}.logo{width:180px;max-height:58px;object-fit:contain}.logo-fallback{width:54px;height:54px;border-radius:14px;background:linear-gradient(135deg,var(--brand),var(--brand2));color:#fff;display:grid;place-items:center;font-size:28px;font-weight:700}.meta{text-align:right}.report-content{padding:34px}.report-content h1{font-size:30px;margin:0 0 20px;border-bottom:3px solid var(--brand);padding-bottom:12px}.report-content h2{font-size:21px;margin:32px 0 12px;color:#0f172a}.report-content h3{font-size:17px;margin:22px 0 10px;color:#1e293b}.report-content p{margin:0 0 12px}.report-content table{width:100%;border-collapse:collapse;margin:14px 0 24px;font-size:13px}.report-content th{background:#f1f5f9;color:#0f172a;text-align:left;font-weight:600}.report-content th,.report-content td{border:1px solid var(--line);padding:8px 10px;vertical-align:top}.report-content tr:nth-child(even) td{background:#fbfdff}.report-content code{background:#f1f5f9;border:1px solid #e2e8f0;border-radius:4px;padding:1px 4px;font-family:Consolas,Monaco,monospace;font-size:12px}.report-content ul{padding-left:22px}.report-content hr{border:0;border-top:1px solid var(--line);margin:30px 0}.report-footer{padding:16px 34px;border-top:1px solid var(--line);background:var(--panel);color:var(--muted);font-size:12px}@media print{body{background:#fff}.report-shell{margin:0;border:0;box-shadow:none;max-width:none}.report-cover,.report-footer{background:#fff}.report-content{padding:24px}a{color:inherit}}
CSS;
    }
}
