<?php

namespace Tests\Feature;

use App\Services\Reports\ReportPresentationService;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

class HtmlPdfReportExportTest extends TestCase
{
    public function test_html_report_renderer_produces_branded_printable_document(): void
    {
        $markdown = "# Sample QA Report\n\n**Project:** Demo API\n\n| Metric | Value |\n|---|---:|\n| Endpoints | 3 |\n\n---\n\nGenerated by **Aptoria v".config('aptoria.version')."**\n";

        $html = app(ReportPresentationService::class)->htmlFromMarkdown($markdown, 'Sample QA Report');

        $this->assertStringContainsString('<!doctype html>', $html);
        $this->assertStringContainsString('<title>Sample QA Report</title>', $html);
        $this->assertStringContainsString('<table>', $html);
        $this->assertStringContainsString('Aptoria', $html);
        $this->assertStringContainsString('report-footer', $html);
        $this->assertStringContainsString('@media print', $html);
    }

    public function test_pdf_report_renderer_produces_pdf_bytes_with_attribution(): void
    {
        $markdown = "# Sample QA Report\n\n**Project:** Demo API\n\n- First check\n- Second check\n";

        $pdf = app(ReportPresentationService::class)->pdfFromMarkdown($markdown, 'Sample QA Report');

        $this->assertStringStartsWith('%PDF-1.4', $pdf);
        $this->assertStringContainsString('Aptoria', $pdf);
        $this->assertStringContainsString('Sample QA Report', $pdf);
        $this->assertStringContainsString('%%EOF', $pdf);
    }

    public function test_core_report_formats_have_markdown_html_and_pdf_routes(): void
    {
        foreach ([
            'projects.reports.full-project.markdown',
            'projects.reports.full-project.html',
            'projects.reports.full-project.pdf',
            'projects.reports.release-readiness.markdown',
            'projects.reports.release-readiness.html',
            'projects.reports.release-readiness.pdf',
            'projects.release-gates.markdown',
            'projects.release-gates.html',
            'projects.release-gates.pdf',
            'projects.reports.scans.markdown',
            'projects.reports.scans.html',
            'projects.reports.scans.pdf',
            'projects.reports.compares.markdown',
            'projects.reports.compares.html',
            'projects.reports.compares.pdf',
            'projects.reports.builder.markdown',
            'projects.reports.builder.html',
            'projects.reports.builder.pdf',
        ] as $route) {
            $this->assertTrue(Route::has($route), $route.' route is missing.');
        }
    }

    public function test_report_center_views_link_to_html_and_pdf_exports(): void
    {
        $files = [
            resource_path('views/reports/project.blade.php'),
            resource_path('views/reports/builder/create.blade.php'),
            resource_path('views/projects/show.blade.php'),
            resource_path('views/scans/show.blade.php'),
            resource_path('views/snapshots/compare-show.blade.php'),
            resource_path('views/release_gates/show.blade.php'),
        ];

        foreach ($files as $file) {
            $content = file_get_contents($file);
            $this->assertStringContainsString('.html', $content, $file.' does not link HTML exports.');
            $this->assertStringContainsString('.pdf', $content, $file.' does not link PDF exports.');
        }
    }

    public function test_readme_links_to_changelog_instead_of_embedding_release_history(): void
    {
        $readme = file_get_contents(base_path('README.md'));

        $this->assertStringContainsString('CHANGELOG.md', $readme);
        $this->assertStringNotContainsString('## v1.0.86', $readme);
        $this->assertStringNotContainsString('## v1.0.84', $readme);
    }
}
