@php($modalId = $modalId ?? 'createReleaseGateModal')
@php($uid = str_replace([':', '.', '#'], '-', $modalId))
<div class="modal fade aptoria-scrollable-form-modal" id="{{ $modalId }}" tabindex="-1" aria-labelledby="{{ $uid }}-label" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable aptoria-scrollable-form-dialog">
        <form method="POST" action="{{ route('projects.release-gates.store', $project) }}" class="modal-content aptoria-form-shell" data-aptoria-form-plugin>
            @csrf
            <input type="hidden" name="_release_gate_modal" value="{{ $modalId }}">
            <div class="modal-header aptoria-scrollable-form-header">
                <div class="d-flex gap-3 align-items-start"><span class="avatar avatar-sm rounded text-bg-primary"><span class="avatar-title"><i data-lucide="workflow"></i></span></span><div><h5 class="modal-title mb-1" id="{{ $uid }}-label">{{ __('messages.release_gates.create_title') }}</h5><p class="text-muted small mb-0">{{ __('messages.release_gates.create_copy') }}</p></div></div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('messages.common.cancel') }}"></button>
            </div>
            <div class="modal-body aptoria-scrollable-form-body">
                <div class="alert alert-light border d-flex gap-2 align-items-start"><i data-lucide="folder-check" class="mt-1"></i><div><strong>{{ __('messages.release_gates.create_notice_title') }}</strong><br><span class="text-muted">{{ __('messages.release_gates.create_notice_copy') }}</span></div></div>
                <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-primary"><span class="avatar-title"><i data-lucide="id-card"></i></span></span><div><h6 class="mb-1">{{ __('messages.release_gates.sections.identity') }}</h6><p class="text-muted small mb-0">{{ __('messages.release_gates.sections.identity_help') }}</p></div></div></div>
                    <div class="row g-3">
                        <div class="col-md-6"><label class="form-label" for="{{ $uid }}-title">{{ __('messages.release_gates.form.title') }}</label><input id="{{ $uid }}-title" name="title" value="{{ old('_release_gate_modal') === $modalId ? old('title') : '' }}" class="form-control @error('title') is-invalid @enderror" required placeholder="{{ __('messages.release_gates.placeholders.title') }}"><div class="form-text">{{ __('messages.release_gates.help.title') }}</div>@error('title')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                        <div class="col-md-3"><label class="form-label" for="{{ $uid }}-release_version">{{ __('messages.release_gates.form.release_version') }}</label><input id="{{ $uid }}-release_version" name="release_version" value="{{ old('_release_gate_modal') === $modalId ? old('release_version') : '' }}" class="form-control @error('release_version') is-invalid @enderror" placeholder="{{ __('messages.release_gates.placeholders.release_version') }}"><div class="form-text">{{ __('messages.release_gates.help.release_version') }}</div>@error('release_version')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                        <div class="col-md-3"><label class="form-label" for="{{ $uid }}-target_environment">{{ __('messages.release_gates.form.target_environment') }}</label><input id="{{ $uid }}-target_environment" name="target_environment" value="{{ old('_release_gate_modal') === $modalId ? old('target_environment') : ($project->environment_label ?? '') }}" class="form-control @error('target_environment') is-invalid @enderror" placeholder="{{ __('messages.release_gates.placeholders.target_environment') }}"><div class="form-text">{{ __('messages.release_gates.help.target_environment') }}</div>@error('target_environment')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                    </div>
                </div>
                <div class="aptoria-form-section"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-warning"><span class="avatar-title"><i data-lucide="shield-chevron"></i></span></span><div><h6 class="mb-1">{{ __('messages.release_gates.sections.profile') }}</h6><p class="text-muted small mb-0">{{ __('messages.release_gates.sections.profile_help') }}</p></div></div></div>
                    <div class="row g-3">
                        <div class="col-md-4"><label class="form-label" for="{{ $uid }}-gate_profile">{{ __('messages.release_gates.form.gate_profile') }}</label><select id="{{ $uid }}-gate_profile" name="gate_profile" class="form-select @error('gate_profile') is-invalid @enderror">@foreach(\App\Models\ReleaseGate::PROFILES as $profile)<option value="{{ $profile }}" @selected((old('_release_gate_modal') === $modalId ? old('gate_profile') : 'standard') === $profile)>{{ __('messages.release_gates.profiles.'.$profile) }}</option>@endforeach</select><div class="form-text">{{ __('messages.release_gates.help.gate_profile') }}</div>@error('gate_profile')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                        <div class="col-md-8"><label class="form-label" for="{{ $uid }}-decision_note">{{ __('messages.release_gates.form.decision_note') }}</label><textarea id="{{ $uid }}-decision_note" name="decision_note" rows="4" class="form-control @error('decision_note') is-invalid @enderror" placeholder="{{ __('messages.release_gates.placeholders.decision_note') }}">{{ old('_release_gate_modal') === $modalId ? old('decision_note') : '' }}</textarea><div class="form-text">{{ __('messages.release_gates.help.decision_note') }}</div>@error('decision_note')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                        <div class="col-12"><div class="form-check"><input class="form-check-input @error('confirm_create_gate') is-invalid @enderror" id="{{ $uid }}-confirm_create_gate" type="checkbox" name="confirm_create_gate" value="1"><label class="form-check-label" for="{{ $uid }}-confirm_create_gate">{{ __('messages.release_gates.form.confirm_create_gate') }}</label>@error('confirm_create_gate')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="form-text">{{ __('messages.release_gates.help.confirm_create_gate') }}</div></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer aptoria-scrollable-form-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('messages.common.cancel') }}</button><button class="btn btn-primary"><i data-lucide="workflow" class="me-1"></i>{{ __('messages.release_gates.create_button') }}</button></div>
        </form>
    </div>
</div>
