@php($uid = str_replace([':', '.', '#'], '-', $modalId))
<div class="modal fade aptoria-scrollable-form-modal" id="{{ $modalId }}" tabindex="-1" aria-labelledby="{{ $uid }}-label" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable aptoria-scrollable-form-dialog">
        <form method="POST" action="{{ route('projects.release-gates.finalize', [$project, $gate]) }}" class="modal-content aptoria-form-shell" data-aptoria-form-plugin>
            @csrf
            <input type="hidden" name="_release_gate_modal" value="{{ $modalId }}">
            <div class="modal-header aptoria-scrollable-form-header"><div class="d-flex gap-3 align-items-start"><span class="avatar avatar-sm rounded text-bg-primary"><span class="avatar-title"><i data-lucide="badge-check"></i></span></span><div><h5 class="modal-title mb-1" id="{{ $uid }}-label">{{ __('messages.release_gates.finalize_gate') }}</h5><p class="text-muted small mb-0">{{ __('messages.release_gates.finalize_copy') }}</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('messages.common.cancel') }}"></button></div>
            <div class="modal-body aptoria-scrollable-form-body">
                @error('final_decision')<div class="alert alert-danger">{{ $message }}</div>@enderror
                <div class="aptoria-form-section"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-warning"><span class="avatar-title"><i data-lucide="shield-chevron"></i></span></span><div><h6 class="mb-1">{{ __('messages.release_gates.sections.final_decision') }}</h6><p class="text-muted small mb-0">{{ __('messages.release_gates.sections.final_decision_help') }}</p></div></div></div>
                    <div class="row g-3"><div class="col-md-4"><label class="form-label" for="{{ $uid }}-final_decision">{{ __('messages.release_gates.final_decision') }}</label><select id="{{ $uid }}-final_decision" name="final_decision" class="form-select @error('final_decision') is-invalid @enderror" required><option value="go" @selected(old('_release_gate_modal') === $modalId && old('final_decision') === 'go')>{{ __('messages.release_gates.final_decisions.go') }}</option><option value="conditional_go" @selected(old('_release_gate_modal') === $modalId && old('final_decision') === 'conditional_go')>{{ __('messages.release_gates.final_decisions.conditional_go') }}</option><option value="no_go" @selected(old('_release_gate_modal') === $modalId && old('final_decision') === 'no_go')>{{ __('messages.release_gates.final_decisions.no_go') }}</option></select><div class="form-text">{{ __('messages.release_gates.help.final_decision') }}</div></div><div class="col-md-8"><label class="form-label" for="{{ $uid }}-decision_note">{{ __('messages.release_gates.form.decision_note') }}</label><textarea id="{{ $uid }}-decision_note" name="decision_note" rows="5" required class="form-control @error('decision_note') is-invalid @enderror" placeholder="{{ __('messages.release_gates.placeholders.final_note') }}">{{ old('_release_gate_modal') === $modalId ? old('decision_note') : '' }}</textarea><div class="form-text">{{ __('messages.release_gates.help.final_note') }}</div>@error('decision_note')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><div class="form-check"><input class="form-check-input @error('confirm_finalize_gate') is-invalid @enderror" id="{{ $uid }}-confirm_finalize_gate" type="checkbox" name="confirm_finalize_gate" value="1"><label class="form-check-label" for="{{ $uid }}-confirm_finalize_gate">{{ __('messages.release_gates.form.confirm_finalize_gate') }}</label>@error('confirm_finalize_gate')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="form-text">{{ __('messages.release_gates.help.confirm_finalize_gate') }}</div></div></div>
                </div>
            </div>
            <div class="modal-footer aptoria-scrollable-form-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('messages.common.cancel') }}</button><button class="btn btn-primary"><i data-lucide="badge-check" class="me-1"></i>{{ __('messages.release_gates.finalize_gate') }}</button></div>
        </form>
    </div>
</div>
