<?php

namespace App\Services\Exports;

use App\Models\Project;
use App\Services\Settings\SettingService;

class ExportCreditService
{
    /** @return array<string, mixed> */
    public function metadata(?string $exportType = null, ?Project $project = null): array
    {
        $metadata = [
            'application' => (string) config('aptoria.product_name', 'Aptoria'),
            'version' => (string) config('aptoria.version'),
            'description' => (string) config('aptoria.positioning', 'Self-hosted API QA, security review and regression monitoring platform.'),
            'repository' => (string) config('aptoria.repository_url', 'https://github.com/Szujo-Janos/Aptoria'),
            'author' => (string) config('aptoria.author', 'János Szujó'),
            'license' => (string) config('aptoria.license_summary', 'Source-available. Free for local evaluation and portfolio/demo use. Commercial redistribution, hosted resale or derivative product use requires written permission.'),
            'generated_at' => now()->toIso8601String(),
        ];

        if ($exportType !== null && $exportType !== '') {
            $metadata['export_type'] = $exportType;
        }

        if ($project instanceof Project) {
            $metadata['project'] = [
                'id' => $project->id,
                'name' => $project->name,
            ];
        }

        return $metadata;
    }

    public function markdownFooter(?string $exportType = null, ?Project $project = null): string
    {
        if (! $this->includeCopyrightFooter()) {
            return '';
        }

        $meta = $this->metadata($exportType, $project);

        return implode("\n", [
            '---',
            '',
            'Generated by **'.$meta['application'].' v'.$meta['version'].'**',
            $meta['description'],
            'Repository: `'.$meta['repository'].'`',
            'Author: **'.$meta['author'].'**',
            'License: '.$meta['license'],
        ]);
    }

    /** @param array<int, string> $lines */
    public function appendMarkdownFooter(array &$lines, ?string $exportType = null, ?Project $project = null): void
    {
        $footer = $this->markdownFooter($exportType, $project);

        if ($footer === '') {
            return;
        }

        foreach (explode("\n", $footer) as $line) {
            $lines[] = $line;
        }
    }

    public function textFile(?string $exportType = null, ?Project $project = null): string
    {
        if (! $this->includeCopyrightFooter()) {
            return '';
        }

        $meta = $this->metadata($exportType, $project);

        $lines = [
            $meta['application'].' v'.$meta['version'],
            '',
            $meta['description'],
            '',
            'Repository: '.$meta['repository'],
            'Author: '.$meta['author'],
            'License: '.$meta['license'],
            'Generated at: '.$meta['generated_at'],
        ];

        if (isset($meta['export_type'])) {
            $lines[] = 'Export type: '.$meta['export_type'];
        }

        if (isset($meta['project']) && is_array($meta['project'])) {
            $lines[] = 'Project: '.$meta['project']['name'].' (#'.$meta['project']['id'].')';
        }

        return implode("\n", $lines)."\n";
    }

    public function shortLine(): string
    {
        if (! $this->includeCopyrightFooter()) {
            return '';
        }

        return sprintf(
            'Generated by %s v%s · %s · Author: %s',
            (string) config('aptoria.product_name', 'Aptoria'),
            (string) config('aptoria.version'),
            (string) config('aptoria.repository_url', 'https://github.com/Szujo-Janos/Aptoria'),
            (string) config('aptoria.author', 'János Szujó')
        );
    }

    private function includeCopyrightFooter(): bool
    {
        return app(SettingService::class)->boolean('report.include_copyright_footer', true);
    }
}
