<?php

return [
    'version' => trim((string) @file_get_contents(base_path('VERSION'))) ?: '0.0.6',
    'product_direction' => 'Evidence-first API QA and release decision platform.',
    'installed_lock_path' => storage_path('app/installed.lock'),
    'setup_token_path' => storage_path('app/setup-token.txt'),
    'default_locale' => 'en',
    'supported_locales' => ['en', 'hu'],
    'supported_locale_names' => [
        'en' => 'English',
        'hu' => 'Magyar',
    ],
    'ui_asset_path' => 'assets/aptoria-ui/assets',
    'domain' => [
        'role' => strtolower((string) env('APTORIA_DOMAIN_ROLE', 'local')),
        'landing_url' => rtrim((string) env('APTORIA_LANDING_URL', env('APP_URL', 'http://127.0.0.1:8000')), '/'),
        'demo_url' => rtrim((string) env('APTORIA_DEMO_URL', 'https://demo.aptoria.dev'), '/'),
        'admin_url' => rtrim((string) env('APTORIA_ADMIN_URL', 'https://admin.aptoria.dev'), '/'),
        'license_url' => rtrim((string) env('APTORIA_LICENSE_URL', 'https://license.aptoria.dev'), '/'),
    ],
    'security' => [
        'session_timeout_minutes' => (int) env('APTORIA_SESSION_TIMEOUT_MINUTES', 120),
        'csp_report_only' => (bool) env('APTORIA_CSP_REPORT_ONLY', true),
    ],
    'links' => [
        'github_url' => rtrim((string) env('APTORIA_GITHUB_URL', 'https://github.com/Szujo-Janos'), '/'),
        'download_url' => rtrim((string) env('APTORIA_DOWNLOAD_URL', 'https://github.com/Szujo-Janos/aptoria/releases'), '/'),
        'docs_url' => rtrim((string) env('APTORIA_DOCS_URL', 'https://github.com/Szujo-Janos/aptoria/tree/main/docs'), '/'),
        'support_url' => rtrim((string) env('APTORIA_SUPPORT_URL', 'https://github.com/Szujo-Janos/aptoria/issues'), '/'),
    ],
    'license' => [
        'required' => filter_var(env('APTORIA_LICENSE_REQUIRED', false), FILTER_VALIDATE_BOOL),
        'mode' => env('APTORIA_LICENSE_MODE', 'local_package'),
        'file_path' => env('APTORIA_LICENSE_FILE', storage_path('app/aptoria-license.json')),
        'public_key' => env('APTORIA_LICENSE_PUBLIC_KEY'),
        'public_key_path' => env('APTORIA_LICENSE_PUBLIC_KEY_PATH', storage_path('app/license-public.pem')),
        'authority' => [
            'url' => env('APTORIA_LICENSE_AUTHORITY_URL', ''),
            'lease_endpoint' => env('APTORIA_LICENSE_AUTHORITY_LEASE_ENDPOINT', '/api/license/runtime-lease'),
            'timeout_seconds' => (int) env('APTORIA_LICENSE_AUTHORITY_TIMEOUT_SECONDS', 8),
            'offline_grace_hours' => (int) env('APTORIA_LICENSE_OFFLINE_GRACE_HOURS', 72),
            'public_key' => env('APTORIA_LICENSE_AUTHORITY_PUBLIC_KEY'),
            'public_key_path' => env('APTORIA_LICENSE_AUTHORITY_PUBLIC_KEY_PATH', storage_path('app/license-authority-public.pem')),
            'lease_cache_path' => env('APTORIA_LICENSE_RUNTIME_LEASE_FILE', storage_path('app/license-runtime-lease.json')),
        ],
    ],
    'deployment' => [
        'smoke_results_path' => env('APTORIA_SMOKE_RESULTS_PATH', storage_path('app/aptoria-deployment/smoke-results')),
        'smoke_result_max_age_hours' => (int) env('APTORIA_SMOKE_RESULT_MAX_AGE_HOURS', 24),
        'smoke_result_history_limit' => (int) env('APTORIA_SMOKE_RESULT_HISTORY_LIMIT', 20),
    ],
    'demo' => [
        'mode' => filter_var(env('APTORIA_DEMO_MODE', false), FILTER_VALIDATE_BOOL),
        'api_base_url' => rtrim((string) env('APTORIA_DEMO_API_BASE_URL', rtrim((string) env('APP_URL', 'http://127.0.0.1:8000'), '/').'/demo-api'), '/'),
        'auth_token' => env('APTORIA_DEMO_API_TOKEN', 'aptoria-demo-token'),
        'allowed_targets' => array_values(array_filter(array_map('trim', explode(',', (string) env('APTORIA_DEMO_ALLOWED_TARGETS', ''))))),
        'viewer_read_only' => filter_var(env('APTORIA_DEMO_VIEWER_READ_ONLY', true), FILTER_VALIDATE_BOOL),
        'viewer_mode' => strtolower(trim((string) env('APTORIA_DEMO_VIEWER_MODE', filter_var(env('APTORIA_DEMO_VIEWER_READ_ONLY', true), FILTER_VALIDATE_BOOL) ? 'readonly' : 'interactive'))),
        'showcase_project_slug' => env('APTORIA_DEMO_SHOWCASE_PROJECT_SLUG', 'aptoria-full-demo-workspace'),
        'auto_open_showcase' => filter_var(env('APTORIA_DEMO_AUTO_OPEN_SHOWCASE', true), FILTER_VALIDATE_BOOL),
        'reset_prune_storage' => filter_var(env('APTORIA_DEMO_RESET_PRUNE_STORAGE', true), FILTER_VALIDATE_BOOL),
        'reset_flush_cache' => filter_var(env('APTORIA_DEMO_RESET_FLUSH_CACHE', true), FILTER_VALIDATE_BOOL),
        'reset_storage_paths' => array_values(array_filter(array_map('trim', explode(',', (string) env('APTORIA_DEMO_RESET_STORAGE_PATHS', 'demo,demo-api,demo-uploads'))))),
        'demo_user_email' => env('APTORIA_DEMO_USER_EMAIL', 'demo@aptoria.dev'),
        'demo_user_password' => env('APTORIA_DEMO_USER_PASSWORD', 'aptoria-demo-2026'),
    ],
    'default_admin' => [
        'name' => 'Aptoria Admin',
        'email' => 'admin@example.com',
        'password' => 'change-me-now',
    ],
];
