@extends('layouts.app')
@section('title', __('messages.native_tests.create_case_title'))
@section('page_title', __('messages.native_tests.create_case_title'))
@section('page_actions')<a href="{{ route('projects.tests.suites.show', [$project, $suite]) }}" class="btn btn-light"><i data-lucide="arrow-left" class="me-1"></i>{{ __('messages.common.cancel') }}</a>@endsection
@section('content')
<form method="POST" action="{{ route('projects.tests.cases.store', [$project, $suite]) }}" class="aptoria-form-shell" data-aptoria-form-plugin>
@csrf
<div class="card aptoria-panel-card">
    <div class="card-header border-light d-flex justify-content-between align-items-start gap-3"><div class="d-flex gap-3 align-items-start"><span class="avatar avatar-sm rounded text-bg-info"><span class="avatar-title"><i data-lucide="clipboard-list"></i></span></span><div><h5 class="card-title mb-1">{{ __('messages.native_tests.create_case_title') }}</h5><p class="text-muted small mb-0">{{ __('messages.native_tests.create_case_copy') }}</p></div></div><span class="badge badge-soft-primary"><i data-lucide="flask-conical" class="me-1"></i>{{ $suite->name }}</span></div>
    <div class="card-body">
        <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-primary"><span class="avatar-title"><i data-lucide="id-card"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.case_identity') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.case_identity_help') }}</p></div></div></div>
            <div class="row g-3">
                <div class="col-md-8"><label class="form-label" for="title">{{ __('messages.native_tests.title_label') }}</label><input id="title" name="title" value="{{ old('title') }}" class="form-control @error('title') is-invalid @enderror" required placeholder="{{ __('messages.native_tests.placeholders.case_title') }}"><div class="form-text">{{ __('messages.native_tests.help.case_title') }}</div>@error('title')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-md-4"><label class="form-label" for="endpoint_id">{{ __('messages.nav.endpoint_inventory') }}</label><select id="endpoint_id" name="endpoint_id" class="form-select @error('endpoint_id') is-invalid @enderror"><option value="">{{ __('messages.native_tests.no_endpoint_link') }}</option>@foreach($endpoints as $endpoint)<option value="{{ $endpoint->id }}" @selected((string)old('endpoint_id')===(string)$endpoint->id)>{{ $endpoint->method }} {{ $endpoint->path }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.endpoint') }}</div>@error('endpoint_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-md-4"><label class="form-label" for="type">{{ __('messages.native_tests.type') }}</label><select id="type" name="type" class="form-select">@foreach(\App\Models\TestCase::TYPES as $type)<option value="{{ $type }}" @selected(old('type','manual')===$type)>{{ __('messages.native_tests.case_types.'.$type) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.type') }}</div></div>
                <div class="col-md-4"><label class="form-label" for="priority">{{ __('messages.native_tests.priority') }}</label><select id="priority" name="priority" class="form-select">@foreach(\App\Models\TestCase::PRIORITIES as $priority)<option value="{{ $priority }}" @selected(old('priority','normal')===$priority)>{{ __('messages.native_tests.priorities.'.$priority) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.priority') }}</div></div>
                <div class="col-md-4"><label class="form-label" for="status">{{ __('messages.common.status') }}</label><select id="status" name="status" class="form-select">@foreach(\App\Models\TestCase::STATUSES as $status)<option value="{{ $status }}" @selected(old('status','active')===$status)>{{ __('messages.native_tests.case_statuses.'.$status) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.case_status') }}</div></div>
            </div>
        </div>
        <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-warning"><span class="avatar-title"><i data-lucide="list-checks"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.procedure') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.procedure_help') }}</p></div></div></div>
            <div class="row g-3"><div class="col-12"><label class="form-label" for="preconditions">{{ __('messages.native_tests.preconditions') }}</label><textarea id="preconditions" name="preconditions" rows="4" class="form-control @error('preconditions') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.preconditions') }}">{{ old('preconditions') }}</textarea><div class="form-text">{{ __('messages.native_tests.help.preconditions') }}</div>@error('preconditions')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="steps">{{ __('messages.native_tests.steps') }}</label><textarea id="steps" name="steps" rows="7" class="form-control @error('steps') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.steps') }}">{{ old('steps') }}</textarea><div class="form-text">{{ __('messages.native_tests.help.steps') }}</div>@error('steps')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="expected_result">{{ __('messages.native_tests.expected_result') }}</label><textarea id="expected_result" name="expected_result" rows="5" class="form-control @error('expected_result') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.expected_result') }}">{{ old('expected_result') }}</textarea><div class="form-text">{{ __('messages.native_tests.help.expected_result') }}</div>@error('expected_result')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
        </div>
        <div class="aptoria-form-section"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-secondary"><span class="avatar-title"><i data-lucide="tags"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.traceability') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.traceability_help') }}</p></div></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="tags">{{ __('messages.native_tests.tags') }}</label><input id="tags" name="tags" value="{{ old('tags') }}" class="form-control @error('tags') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.tags') }}"><div class="form-text">{{ __('messages.native_tests.help.tags') }}</div>@error('tags')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="external_reference">{{ __('messages.native_tests.external_reference') }}</label><input id="external_reference" name="external_reference" value="{{ old('external_reference') }}" class="form-control @error('external_reference') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.external_reference') }}"><div class="form-text">{{ __('messages.native_tests.help.external_reference') }}</div>@error('external_reference')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div></div>
    </div>
    <div class="card-footer aptoria-card-footer-subtle d-flex justify-content-end gap-2"><a href="{{ route('projects.tests.suites.show', [$project, $suite]) }}" class="btn btn-light">{{ __('messages.common.cancel') }}</a><button class="btn btn-primary"><i data-lucide="save" class="me-1"></i>{{ __('messages.common.save') }}</button></div>
</div>
</form>
@endsection
