@extends('layouts.app')
@section('title', $suite->name)
@section('page_title', $suite->name)
@section('page_actions')
    <a href="{{ route('projects.tests.index', $project) }}" class="btn btn-light"><i data-lucide="arrow-left" class="me-1"></i>{{ __('messages.native_tests.back_to_tests') }}</a>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createCaseModal{{ $suite->id }}"><i data-lucide="clipboard-plus" class="me-1"></i>{{ __('messages.native_tests.new_case') }}</button>
@endsection
@section('content')
<div class="row g-3 mb-3">
    <div class="col-lg-4"><div class="card h-100 aptoria-panel-card"><div class="card-body"><div class="d-flex gap-3 align-items-start"><span class="avatar avatar-md rounded text-bg-primary"><span class="avatar-title"><i data-lucide="flask-conical"></i></span></span><div><h5 class="mb-1">{{ $suite->name }}</h5><p class="text-muted mb-3">{{ $suite->description ?: __('messages.native_tests.no_description') }}</p><span class="badge badge-soft-{{ $suite->status_tone }} me-1">{{ $suite->status_label }}</span><span class="badge badge-soft-{{ $suite->priority_tone }}">{{ $suite->priority_label }}</span></div></div></div><div class="card-footer aptoria-card-footer-subtle text-muted">{{ __('messages.native_tests.owner_name') }}: {{ $suite->owner_name ?: __('messages.common.not_available') }}</div></div></div>
    <div class="col-lg-8"><div class="row g-3"><div class="col-md-4"><div class="card h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar avatar-md rounded text-bg-info"><span class="avatar-title"><i data-lucide="clipboard-list"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.native_tests.cases') }}</p><h3 class="mb-0 fw-light">{{ $cases->count() }}</h3></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar avatar-md rounded text-bg-success"><span class="avatar-title"><i data-lucide="play"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.native_tests.runs') }}</p><h3 class="mb-0 fw-light">{{ $runs->count() }}</h3></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar avatar-md rounded text-bg-warning"><span class="avatar-title"><i data-lucide="folder-check"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.native_tests.repository_evidence') }}</p><h3 class="mb-0 fw-light">{{ $runs->whereNotNull('finding_evidence_id')->count() }}</h3></div></div></div></div></div></div>
</div>

<div class="card aptoria-table-card aptoria-panel-card mb-3">
    <div class="card-header border-light justify-content-between align-items-center"><div class="d-flex gap-3 align-items-center"><span class="avatar avatar-sm rounded text-bg-info"><span class="avatar-title"><i data-lucide="clipboard-list"></i></span></span><div><h5 class="card-title mb-1">{{ __('messages.native_tests.cases_title') }}</h5><p class="text-muted mb-0 small">{{ __('messages.native_tests.cases_copy') }}</p></div></div><button type="button" class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#createCaseModal{{ $suite->id }}"><i data-lucide="clipboard-plus" class="me-1"></i>{{ __('messages.native_tests.new_case') }}</button></div>
    <div class="card-body"><div class="table-responsive"><table data-tables="native-test-cases" data-aptoria-paging="true" class="table table-custom table-striped table-nowrap table-centered mb-0 w-100 aptoria-resource-table"><thead class="thead-sm text-uppercase fs-xxs"><tr><th>{{ __('messages.native_tests.case') }}</th><th>{{ __('messages.nav.endpoint_inventory') }}</th><th>{{ __('messages.common.status') }}</th><th>{{ __('messages.native_tests.last_run') }}</th><th>{{ __('messages.native_tests.runs') }}</th><th class="text-end aptoria-actions-cell">{{ __('messages.common.actions') }}</th></tr></thead><tbody>
    @forelse($cases as $case)
        <tr><td><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-info"><span class="avatar-title"><i data-lucide="{{ $case->type_icon }}"></i></span></span><div><a class="fw-medium text-body" href="{{ route('projects.tests.cases.show', [$project, $case]) }}">{{ $case->title }}</a><small class="text-muted d-block">{{ $case->type_label }} · {{ $case->priority_label }}</small></div></div></td><td>@if($case->endpoint)<span class="badge badge-soft-primary"><i data-lucide="route" class="me-1"></i>{{ $case->endpoint->method }} {{ $case->endpoint->path }}</span>@else<span class="text-muted">—</span>@endif</td><td><span class="badge badge-soft-{{ $case->status_tone }}">{{ $case->status_label }}</span></td><td>@if($case->last_run_status)<span class="badge badge-soft-{{ $case->last_run_tone }}">{{ __('messages.native_tests.run_statuses.'.$case->last_run_status) }}</span><small class="text-muted d-block">{{ $case->last_run_at?->format('Y-m-d H:i') }}</small>@else<span class="text-muted">{{ __('messages.native_tests.not_run') }}</span>@endif</td><td>{{ $case->runs_count }}</td><td class="text-end"><div class="dropdown"><button class="btn btn-light btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown">{{ __('messages.common.actions') }}</button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('projects.tests.cases.show', [$project, $case]) }}"><i data-lucide="eye" class="me-2"></i>{{ __('messages.common.view') }}</a><a class="dropdown-item" href="{{ route('projects.tests.cases.show', [$project, $case]) }}"><i data-lucide="play" class="me-2"></i>{{ __('messages.native_tests.record_run') }}</a></div></div></td></tr>
    @empty
        <tr><td colspan="6" class="text-center text-muted py-5">{{ __('messages.native_tests.empty_cases') }}</td></tr>
    @endforelse
    </tbody></table></div></div>
</div>
@include('native_tests.partials.create-case-modal', ['project' => $project, 'suite' => $suite, 'endpoints' => $endpoints, 'modalId' => 'createCaseModal'.$suite->id])
@include('native_tests.partials.reopen-modal-script')
@endsection
