@extends('layouts.app')
@section('title', $case->title)
@section('page_title', $case->title)
@section('page_actions')
    <a href="{{ route('projects.tests.suites.show', [$project, $case->suite]) }}" class="btn btn-light"><i data-lucide="arrow-left" class="me-1"></i>{{ __('messages.native_tests.back_to_suite') }}</a>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#recordRunModal{{ $case->id }}"><i data-lucide="play" class="me-1"></i>{{ __('messages.native_tests.record_run') }}</button>
@endsection
@section('content')
<div class="row g-3 mb-3">
    <div class="col-xl-5"><div class="card h-100 aptoria-panel-card"><div class="card-header border-light"><div class="d-flex gap-3 align-items-start"><span class="avatar avatar-sm rounded text-bg-info"><span class="avatar-title"><i data-lucide="{{ $case->type_icon }}"></i></span></span><div><h5 class="card-title mb-1">{{ __('messages.native_tests.case_context') }}</h5><p class="text-muted mb-0 small">{{ __('messages.native_tests.case_context_copy') }}</p></div></div></div><div class="card-body"><div class="d-flex flex-wrap gap-2 mb-3"><span class="badge badge-soft-{{ $case->status_tone }}">{{ $case->status_label }}</span><span class="badge badge-soft-{{ $case->priority_tone }}">{{ $case->priority_label }}</span><span class="badge badge-soft-info"><i data-lucide="{{ $case->type_icon }}" class="me-1"></i>{{ $case->type_label }}</span></div><p class="text-muted mb-2">{{ $case->description ?: __('messages.native_tests.no_description') }}</p>@if($case->endpoint)<span class="badge badge-soft-primary"><i data-lucide="route" class="me-1"></i>{{ $case->endpoint->method }} {{ $case->endpoint->path }}</span>@endif</div><div class="card-footer aptoria-card-footer-subtle text-muted">{{ __('messages.native_tests.suite') }}: {{ $case->suite->name }}</div></div></div>
    <div class="col-xl-7"><div class="row g-3"><div class="col-md-4"><div class="card h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar avatar-md rounded text-bg-success"><span class="avatar-title"><i data-lucide="play"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.native_tests.runs') }}</p><h3 class="mb-0 fw-light">{{ $case->run_count }}</h3></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar avatar-md rounded text-bg-success"><span class="avatar-title"><i data-lucide="badge-check"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.native_tests.passed') }}</p><h3 class="mb-0 fw-light">{{ $case->pass_count }}</h3></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar avatar-md rounded text-bg-danger"><span class="avatar-title"><i data-lucide="circle-x"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.native_tests.failed') }}</p><h3 class="mb-0 fw-light">{{ $case->fail_count }}</h3></div></div></div></div></div></div>
</div>

<div class="row g-3 mb-3">
    <div class="col-lg-4"><div class="card h-100 aptoria-panel-card"><div class="card-header border-light"><h5 class="card-title mb-1"><i data-lucide="list-checks" class="me-2"></i>{{ __('messages.native_tests.preconditions') }}</h5></div><div class="card-body"><p class="text-muted white-space-pre-line mb-0">{{ $case->preconditions ?: __('messages.common.not_available') }}</p></div></div></div>
    <div class="col-lg-4"><div class="card h-100 aptoria-panel-card"><div class="card-header border-light"><h5 class="card-title mb-1"><i data-lucide="clipboard-list" class="me-2"></i>{{ __('messages.native_tests.steps') }}</h5></div><div class="card-body"><p class="text-muted white-space-pre-line mb-0">{{ $case->steps ?: __('messages.common.not_available') }}</p></div></div></div>
    <div class="col-lg-4"><div class="card h-100 aptoria-panel-card"><div class="card-header border-light"><h5 class="card-title mb-1"><i data-lucide="badge-check" class="me-2"></i>{{ __('messages.native_tests.expected_result') }}</h5></div><div class="card-body"><p class="text-muted white-space-pre-line mb-0">{{ $case->expected_result ?: __('messages.common.not_available') }}</p></div></div></div>
</div>

<div class="card aptoria-table-card aptoria-panel-card">
    <div class="card-header border-light justify-content-between align-items-center"><div class="d-flex gap-3 align-items-center"><span class="avatar avatar-sm rounded text-bg-success"><span class="avatar-title"><i data-lucide="play"></i></span></span><div><h5 class="card-title mb-1">{{ __('messages.native_tests.runs_title') }}</h5><p class="text-muted mb-0 small">{{ __('messages.native_tests.runs_copy') }}</p></div></div><button type="button" class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#recordRunModal{{ $case->id }}"><i data-lucide="play" class="me-1"></i>{{ __('messages.native_tests.record_run') }}</button></div>
    <div class="card-body"><div class="table-responsive"><table data-tables="native-test-runs" data-aptoria-paging="true" class="table table-custom table-striped table-nowrap table-centered mb-0 w-100 aptoria-resource-table"><thead class="thead-sm text-uppercase fs-xxs"><tr><th>{{ __('messages.common.status') }}</th><th>{{ __('messages.native_tests.executed_at') }}</th><th>{{ __('messages.native_tests.duration_ms') }}</th><th>{{ __('messages.evidence.evidence') }}</th><th>{{ __('messages.findings.finding') }}</th></tr></thead><tbody>
    @forelse($runs as $run)
        <tr><td><span class="badge badge-soft-{{ $run->status_tone }}"><i data-lucide="{{ $run->status_icon }}" class="me-1"></i>{{ $run->status_label }}</span></td><td>{{ $run->executed_at?->format('Y-m-d H:i') ?: __('messages.common.not_available') }}<small class="text-muted d-block">{{ $run->executedBy?->name ?: __('messages.common.system') }}</small></td><td>{{ $run->duration_ms ? number_format($run->duration_ms).' ms' : '—' }}</td><td>@if($run->evidence)<a href="{{ route('projects.evidence.show', [$project, $run->evidence]) }}" class="badge badge-soft-success"><i data-lucide="folder-check" class="me-1"></i>#{{ $run->evidence->id }}</a>@else<span class="text-muted">—</span>@endif</td><td>@if($run->finding)<a href="{{ route('projects.findings.show', [$project, $run->finding]) }}" class="badge badge-soft-danger"><i data-lucide="bug" class="me-1"></i>#{{ $run->finding->id }}</a>@else<span class="text-muted">—</span>@endif</td></tr>
    @empty
        <tr><td colspan="5" class="text-center text-muted py-5">{{ __('messages.native_tests.empty_runs') }}</td></tr>
    @endforelse
    </tbody></table></div></div>
</div>
@include('native_tests.partials.record-run-modal', ['project' => $project, 'case' => $case, 'modalId' => 'recordRunModal'.$case->id])
@include('native_tests.partials.reopen-modal-script')
@endsection
