<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Aptoria monitor alert</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.5; color: #1f2937;">
    <h1 style="font-size: 20px; margin-bottom: 8px;">Aptoria monitor alert</h1>
    <p style="margin-top: 0; color: #6b7280;">A scheduled monitor changed state.</p>

    <table cellpadding="6" cellspacing="0" border="0" style="border-collapse: collapse; width: 100%; max-width: 720px;">
        <tr><th align="left">Project</th><td>{{ $payload['project'] ?? '-' }}</td></tr>
        <tr><th align="left">Monitor</th><td>{{ $payload['monitor'] ?? '-' }}</td></tr>
        <tr><th align="left">Status</th><td><strong>{{ $payload['status'] ?? '-' }}</strong></td></tr>
        <tr><th align="left">Previous status</th><td>{{ $payload['previous_status'] ?? '-' }}</td></tr>
        <tr><th align="left">Severity</th><td>{{ $payload['severity'] ?? '-' }}</td></tr>
        <tr><th align="left">Message</th><td>{{ $payload['message'] ?? '-' }}</td></tr>
        <tr><th align="left">Triggered at</th><td>{{ $payload['triggered_at'] ?? '-' }}</td></tr>
        <tr><th align="left">Next run</th><td>{{ $payload['next_run_at'] ?? '-' }}</td></tr>
    </table>

    <p style="margin-top: 24px; color: #6b7280; font-size: 13px;">This message was generated by Aptoria. Review the monitor in the self-hosted dashboard for scan, snapshot and compare evidence.</p>
</body>
</html>
