@extends('layouts.app')
@section('title', __('messages.finding_dedup.title'))
@section('page_title', __('messages.finding_dedup.title'))
@section('page_actions')
    <a href="{{ route('projects.findings.index', $project) }}" class="btn btn-light"><i data-lucide="arrow-left" class="me-1"></i>{{ __('messages.nav.findings') }}</a>
    <form method="POST" action="{{ route('projects.findings.dedup.scan', $project) }}" class="d-inline" data-aptoria-confirm="warning" data-confirm-title="{{ __('messages.finding_dedup.scan_confirm_title') }}" data-confirm-text="{{ __('messages.finding_dedup.scan_confirm_text') }}" data-confirm-button="{{ __('messages.finding_dedup.scan') }}">@csrf<button class="btn btn-primary"><i data-lucide="scan-search" class="me-1"></i>{{ __('messages.finding_dedup.scan') }}</button></form>
@endsection
@section('content')
<div class="row g-3 mb-3"><div class="col-xl-8"><div class="card aptoria-panel-card"><div class="card-body"><span class="badge badge-soft-primary badge-label mb-2"><i class="ti ti-point-filled"></i>{{ __('messages.finding_dedup.merge_workflow') }}</span><h2 class="fw-normal mb-2"><i data-lucide="combine" class="me-2"></i>{{ __('messages.finding_dedup.heading') }}</h2><p class="text-muted mb-0">{{ __('messages.finding_dedup.copy') }}</p></div><div class="card-footer aptoria-card-footer-subtle text-muted">{{ __('messages.finding_dedup.footer') }}</div></div></div><div class="col-xl-4"><div class="card aptoria-panel-card"><div class="card-body d-flex align-items-center gap-3"><span class="avatar avatar-md rounded text-bg-warning"><span class="avatar-title"><i data-lucide="copy-check"></i></span></span><div><p class="text-muted mb-1">{{ __('messages.finding_dedup.candidates') }}</p><h3 class="fw-light mb-0">{{ $candidates->where('status','candidate')->count() }}</h3></div></div></div></div></div>
<div class="card aptoria-table-card aptoria-panel-card mb-3"><div class="card-header border-light justify-content-between align-items-center"><div><h5 class="card-title mb-1"><i data-lucide="copy-check" class="me-2"></i>{{ __('messages.finding_dedup.candidate_table') }}</h5><p class="text-muted small mb-0">{{ __('messages.finding_dedup.candidate_copy') }}</p></div><span class="badge badge-soft-primary">{{ $candidates->count() }}</span></div><div class="card-body p-0"><div class="table-responsive"><table data-tables="finding-dedup" class="table table-custom table-striped table-nowrap table-centered mb-0 w-100 aptoria-resource-table"><thead><tr><th>{{ __('messages.finding_dedup.primary') }}</th><th>{{ __('messages.finding_dedup.duplicate') }}</th><th>{{ __('messages.finding_dedup.score') }}</th><th>{{ __('messages.common.status') }}</th><th class="text-end aptoria-actions-cell">{{ __('messages.common.actions') }}</th></tr></thead><tbody>
@forelse($candidates as $candidate)
<tr><td><a class="fw-medium text-body" href="{{ route('projects.findings.show', [$project, $candidate->primaryFinding]) }}">{{ $candidate->primaryFinding?->title }}</a><small class="text-muted d-block">{{ $candidate->primaryFinding?->endpoint?->method }} {{ $candidate->primaryFinding?->endpoint?->path }}</small></td><td><a class="fw-medium text-body" href="{{ route('projects.findings.show', [$project, $candidate->duplicateFinding]) }}">{{ $candidate->duplicateFinding?->title }}</a><small class="text-muted d-block">{{ $candidate->duplicateFinding?->endpoint?->method }} {{ $candidate->duplicateFinding?->endpoint?->path }}</small></td><td><span class="badge badge-soft-{{ $candidate->score_tone }} badge-label"><i class="ti ti-point-filled"></i>{{ $candidate->score }}%</span></td><td><span class="badge badge-soft-secondary">{{ $candidate->status_label }}</span></td><td class="text-end aptoria-actions-cell">@if($candidate->status === 'candidate')<div class="dropdown"><button class="btn btn-light btn-icon btn-sm rounded-circle" data-bs-toggle="dropdown"><i class="ti ti-dots"></i></button><div class="dropdown-menu dropdown-menu-end"><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#mergeCandidate{{ $candidate->id }}"><i data-lucide="combine" class="me-2"></i>{{ __('messages.finding_dedup.merge') }}</button><form method="POST" action="{{ route('projects.findings.dedup.dismiss', [$project, $candidate]) }}">@csrf<button class="dropdown-item"><i data-lucide="x-circle" class="me-2"></i>{{ __('messages.finding_dedup.dismiss') }}</button></form></div></div>@else<span class="text-muted">—</span>@endif</td></tr>
@empty<tr><td colspan="5" class="text-center text-muted py-5">{{ __('messages.finding_dedup.empty') }}</td></tr>@endforelse
</tbody></table></div></div></div>

@foreach($candidates as $candidate)
<div class="modal fade" id="mergeCandidate{{ $candidate->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form method="POST" action="{{ route('projects.findings.dedup.merge', [$project, $candidate]) }}" class="modal-content" data-aptoria-form-plugin>@csrf<div class="modal-header"><h5 class="modal-title"><i data-lucide="combine" class="me-2"></i>{{ __('messages.finding_dedup.merge') }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="text-muted">{{ __('messages.finding_dedup.merge_help') }}</p><div class="alert alert-light border"><strong>{{ $candidate->duplicateFinding?->title }}</strong><br><span class="text-muted">→ {{ $candidate->primaryFinding?->title }}</span></div><label class="form-label">{{ __('messages.finding_dedup.merge_note') }}</label><textarea name="merge_note" class="form-control" rows="3" placeholder="{{ __('messages.finding_dedup.merge_note_placeholder') }}"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('messages.common.cancel') }}</button><button class="btn btn-primary"><i data-lucide="combine" class="me-1"></i>{{ __('messages.finding_dedup.merge') }}</button></div></form></div></div>
@endforeach

@if($mergedFindings->count())<div class="card aptoria-panel-card"><div class="card-header border-light"><h5 class="card-title mb-0"><i data-lucide="history" class="me-2"></i>{{ __('messages.finding_dedup.merged_history') }}</h5></div><div class="card-body"><div class="list-group list-group-flush">@foreach($mergedFindings as $finding)<div class="list-group-item px-0"><span class="fw-medium">{{ $finding->title }}</span><span class="text-muted"> → {{ $finding->mergedInto?->title }}</span><small class="text-muted d-block">{{ $finding->merged_at?->format('Y-m-d H:i') }}</small></div>@endforeach</div></div></div>@endif
@endsection
