@php($modalId = $modalId ?? 'createCaseModal')
@php($uid = str_replace([':', '.', '#'], '-', $modalId))
<div class="modal fade aptoria-scrollable-form-modal" id="{{ $modalId }}" tabindex="-1" aria-labelledby="{{ $uid }}-label" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable aptoria-scrollable-form-dialog">
        <form method="POST" action="{{ route('projects.tests.cases.store', [$project, $suite]) }}" class="modal-content aptoria-form-shell" data-aptoria-form-plugin>
            @csrf
            <input type="hidden" name="_native_test_modal" value="{{ $modalId }}">
            <div class="modal-header aptoria-scrollable-form-header">
                <div class="d-flex gap-3 align-items-start">
                    <span class="avatar avatar-sm rounded text-bg-info"><span class="avatar-title"><i data-lucide="clipboard-plus"></i></span></span>
                    <div><h5 class="modal-title mb-1" id="{{ $uid }}-label">{{ __('messages.native_tests.create_case_title') }}</h5><p class="text-muted small mb-0">{{ __('messages.native_tests.create_case_copy') }}</p></div>
                </div>
                <span class="badge badge-soft-primary d-none d-md-inline-flex"><i data-lucide="flask-conical" class="me-1"></i>{{ $suite->name }}</span>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('messages.common.cancel') }}"></button>
            </div>
            <div class="modal-body aptoria-scrollable-form-body">
                <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-primary"><span class="avatar-title"><i data-lucide="id-card"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.case_identity') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.case_identity_help') }}</p></div></div></div>
                    <div class="row g-3">
                        <div class="col-md-8"><label class="form-label" for="{{ $uid }}-title">{{ __('messages.native_tests.title_label') }}</label><input id="{{ $uid }}-title" name="title" value="{{ old('_native_test_modal') === $modalId ? old('title') : '' }}" class="form-control @error('title') is-invalid @enderror" required placeholder="{{ __('messages.native_tests.placeholders.case_title') }}"><div class="form-text">{{ __('messages.native_tests.help.case_title') }}</div>@error('title')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                        <div class="col-md-4"><label class="form-label" for="{{ $uid }}-endpoint_id">{{ __('messages.nav.endpoint_inventory') }}</label><select id="{{ $uid }}-endpoint_id" name="endpoint_id" class="form-select @error('endpoint_id') is-invalid @enderror"><option value="">{{ __('messages.native_tests.no_endpoint_link') }}</option>@foreach($endpoints as $endpoint)<option value="{{ $endpoint->id }}" @selected((string)(old('_native_test_modal') === $modalId ? old('endpoint_id') : '')===(string)$endpoint->id)>{{ $endpoint->method }} {{ $endpoint->path }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.endpoint') }}</div>@error('endpoint_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                        <div class="col-md-4"><label class="form-label" for="{{ $uid }}-type">{{ __('messages.native_tests.type') }}</label><select id="{{ $uid }}-type" name="type" class="form-select">@foreach(\App\Models\TestCase::TYPES as $type)<option value="{{ $type }}" @selected((old('_native_test_modal') === $modalId ? old('type') : 'manual')===$type)>{{ __('messages.native_tests.case_types.'.$type) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.type') }}</div></div>
                        <div class="col-md-4"><label class="form-label" for="{{ $uid }}-priority">{{ __('messages.native_tests.priority') }}</label><select id="{{ $uid }}-priority" name="priority" class="form-select">@foreach(\App\Models\TestCase::PRIORITIES as $priority)<option value="{{ $priority }}" @selected((old('_native_test_modal') === $modalId ? old('priority') : 'normal')===$priority)>{{ __('messages.native_tests.priorities.'.$priority) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.priority') }}</div></div>
                        <div class="col-md-4"><label class="form-label" for="{{ $uid }}-status">{{ __('messages.common.status') }}</label><select id="{{ $uid }}-status" name="status" class="form-select">@foreach(\App\Models\TestCase::STATUSES as $status)<option value="{{ $status }}" @selected((old('_native_test_modal') === $modalId ? old('status') : 'active')===$status)>{{ __('messages.native_tests.case_statuses.'.$status) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.case_status') }}</div></div>
                    </div>
                </div>
                <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-warning"><span class="avatar-title"><i data-lucide="list-checks"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.procedure') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.procedure_help') }}</p></div></div></div>
                    <div class="row g-3"><div class="col-12"><label class="form-label" for="{{ $uid }}-preconditions">{{ __('messages.native_tests.preconditions') }}</label><textarea id="{{ $uid }}-preconditions" name="preconditions" rows="4" class="form-control @error('preconditions') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.preconditions') }}">{{ old('_native_test_modal') === $modalId ? old('preconditions') : '' }}</textarea><div class="form-text">{{ __('messages.native_tests.help.preconditions') }}</div>@error('preconditions')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="{{ $uid }}-steps">{{ __('messages.native_tests.steps') }}</label><textarea id="{{ $uid }}-steps" name="steps" rows="7" class="form-control @error('steps') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.steps') }}">{{ old('_native_test_modal') === $modalId ? old('steps') : '' }}</textarea><div class="form-text">{{ __('messages.native_tests.help.steps') }}</div>@error('steps')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="{{ $uid }}-expected_result">{{ __('messages.native_tests.expected_result') }}</label><textarea id="{{ $uid }}-expected_result" name="expected_result" rows="5" class="form-control @error('expected_result') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.expected_result') }}">{{ old('_native_test_modal') === $modalId ? old('expected_result') : '' }}</textarea><div class="form-text">{{ __('messages.native_tests.help.expected_result') }}</div>@error('expected_result')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
                </div>
                <div class="aptoria-form-section"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-secondary"><span class="avatar-title"><i data-lucide="tags"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.traceability') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.traceability_help') }}</p></div></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="{{ $uid }}-tags">{{ __('messages.native_tests.tags') }}</label><input id="{{ $uid }}-tags" name="tags" value="{{ old('_native_test_modal') === $modalId ? old('tags') : '' }}" class="form-control @error('tags') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.tags') }}"><div class="form-text">{{ __('messages.native_tests.help.tags') }}</div>@error('tags')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="{{ $uid }}-external_reference">{{ __('messages.native_tests.external_reference') }}</label><input id="{{ $uid }}-external_reference" name="external_reference" value="{{ old('_native_test_modal') === $modalId ? old('external_reference') : '' }}" class="form-control @error('external_reference') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.external_reference') }}"><div class="form-text">{{ __('messages.native_tests.help.external_reference') }}</div>@error('external_reference')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div></div>
            </div>
            <div class="modal-footer aptoria-scrollable-form-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('messages.common.cancel') }}</button><button class="btn btn-primary"><i data-lucide="save" class="me-1"></i>{{ __('messages.common.save') }}</button></div>
        </form>
    </div>
</div>
