@php($modalId = $modalId ?? 'recordRunModal')
@php($uid = str_replace([':', '.', '#'], '-', $modalId))
<div class="modal fade aptoria-scrollable-form-modal" id="{{ $modalId }}" tabindex="-1" aria-labelledby="{{ $uid }}-label" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable aptoria-scrollable-form-dialog">
        <form method="POST" action="{{ route('projects.tests.runs.store', [$project, $case]) }}" class="modal-content aptoria-form-shell" data-aptoria-form-plugin data-aptoria-confirm="warning" data-confirm-title="{{ __('messages.native_tests.confirm_run_title') }}" data-confirm-text="{{ __('messages.native_tests.confirm_run_text') }}" data-confirm-button="{{ __('messages.native_tests.confirm_run_button') }}">
            @csrf
            <input type="hidden" name="_native_test_modal" value="{{ $modalId }}">
            <div class="modal-header aptoria-scrollable-form-header">
                <div class="d-flex gap-3 align-items-start"><span class="avatar avatar-sm rounded text-bg-success"><span class="avatar-title"><i data-lucide="play"></i></span></span><div><h5 class="modal-title mb-1" id="{{ $uid }}-label">{{ __('messages.native_tests.record_run_title') }}</h5><p class="text-muted small mb-0">{{ __('messages.native_tests.record_run_copy') }}</p></div></div>
                <span class="badge badge-soft-info d-none d-md-inline-flex"><i data-lucide="folder-check" class="me-1"></i>{{ __('messages.native_tests.evidence_created_automatically') }}</span>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('messages.common.cancel') }}"></button>
            </div>
            <div class="modal-body aptoria-scrollable-form-body">
                <div class="alert alert-light border d-flex gap-2 align-items-start"><i data-lucide="fingerprint" class="mt-1"></i><div><strong>{{ __('messages.native_tests.repository_notice_title') }}</strong><br><span class="text-muted">{{ __('messages.native_tests.repository_notice_copy') }}</span></div></div>
                <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-primary"><span class="avatar-title"><i data-lucide="id-card"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.run_identity') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.run_identity_help') }}</p></div></div></div>
                    <div class="row g-3"><div class="col-md-3"><label class="form-label" for="{{ $uid }}-status">{{ __('messages.common.status') }}</label><select id="{{ $uid }}-status" name="status" class="form-select @error('status') is-invalid @enderror" required>@foreach(\App\Models\TestRun::STATUSES as $status)<option value="{{ $status }}" @selected((old('_native_test_modal') === $modalId ? old('status') : 'pass')===$status)>{{ __('messages.native_tests.run_statuses.'.$status) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.run_status') }}</div>@error('status')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label" for="{{ $uid }}-executed_at">{{ __('messages.native_tests.executed_at') }}</label><input id="{{ $uid }}-executed_at" type="datetime-local" name="executed_at" value="{{ old('_native_test_modal') === $modalId ? old('executed_at') : '' }}" class="form-control @error('executed_at') is-invalid @enderror"><div class="form-text">{{ __('messages.native_tests.help.executed_at') }}</div>@error('executed_at')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label" for="{{ $uid }}-duration_ms">{{ __('messages.native_tests.duration_ms') }}</label><input id="{{ $uid }}-duration_ms" type="number" min="0" name="duration_ms" value="{{ old('_native_test_modal') === $modalId ? old('duration_ms') : '' }}" class="form-control @error('duration_ms') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.duration_ms') }}"><div class="form-text">{{ __('messages.native_tests.help.duration_ms') }}</div>@error('duration_ms')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label" for="{{ $uid }}-environment_label">{{ __('messages.native_tests.environment_label') }}</label><input id="{{ $uid }}-environment_label" name="environment_label" value="{{ old('_native_test_modal') === $modalId ? old('environment_label') : '' }}" class="form-control @error('environment_label') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.environment_label') }}"><div class="form-text">{{ __('messages.native_tests.help.environment_label') }}</div>@error('environment_label')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
                </div>
                <div class="aptoria-form-section mb-3"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-info"><span class="avatar-title"><i data-lucide="file-delta"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.run_result') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.run_result_help') }}</p></div></div></div><div class="row g-3"><div class="col-12"><label class="form-label" for="{{ $uid }}-actual_result">{{ __('messages.native_tests.actual_result') }}</label><textarea id="{{ $uid }}-actual_result" name="actual_result" rows="5" class="form-control @error('actual_result') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.actual_result') }}">{{ old('_native_test_modal') === $modalId ? old('actual_result') : '' }}</textarea><div class="form-text">{{ __('messages.native_tests.help.actual_result') }}</div>@error('actual_result')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="{{ $uid }}-failure_summary">{{ __('messages.native_tests.failure_summary') }}</label><textarea id="{{ $uid }}-failure_summary" name="failure_summary" rows="4" class="form-control @error('failure_summary') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.failure_summary') }}">{{ old('_native_test_modal') === $modalId ? old('failure_summary') : '' }}</textarea><div class="form-text">{{ __('messages.native_tests.help.failure_summary') }}</div>@error('failure_summary')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="{{ $uid }}-evidence_summary">{{ __('messages.native_tests.evidence_summary') }}</label><textarea id="{{ $uid }}-evidence_summary" name="evidence_summary" rows="4" class="form-control @error('evidence_summary') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.evidence_summary') }}">{{ old('_native_test_modal') === $modalId ? old('evidence_summary') : '' }}</textarea><div class="form-text">{{ __('messages.native_tests.help.evidence_summary') }}</div>@error('evidence_summary')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div></div>
                <div class="aptoria-form-section"><div class="aptoria-form-section-header"><div class="d-flex gap-2 align-items-start"><span class="avatar avatar-xs rounded text-bg-danger"><span class="avatar-title"><i data-lucide="bug"></i></span></span><div><h6 class="mb-1">{{ __('messages.native_tests.sections.failure_finding') }}</h6><p class="text-muted small mb-0">{{ __('messages.native_tests.sections.failure_finding_help') }}</p></div></div></div><div class="row g-3"><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="create_finding" value="1" id="{{ $uid }}-create_finding" @checked(old('_native_test_modal') === $modalId ? old('create_finding', true) : true)><label class="form-check-label" for="{{ $uid }}-create_finding">{{ __('messages.native_tests.create_finding') }}</label></div><div class="form-text">{{ __('messages.native_tests.help.create_finding') }}</div></div><div class="col-md-6"><label class="form-label" for="{{ $uid }}-finding_title">{{ __('messages.native_tests.finding_title') }}</label><input id="{{ $uid }}-finding_title" name="finding_title" value="{{ old('_native_test_modal') === $modalId ? old('finding_title') : '' }}" class="form-control @error('finding_title') is-invalid @enderror" placeholder="{{ __('messages.native_tests.placeholders.finding_title') }}"><div class="form-text">{{ __('messages.native_tests.help.finding_title') }}</div>@error('finding_title')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label" for="{{ $uid }}-finding_severity">{{ __('messages.findings.severity') }}</label><select id="{{ $uid }}-finding_severity" name="finding_severity" class="form-select">@foreach(\App\Models\Finding::SEVERITIES as $severity)<option value="{{ $severity }}" @selected((old('_native_test_modal') === $modalId ? old('finding_severity') : 'medium')===$severity)>{{ __('messages.findings.severities.'.$severity) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.finding_severity') }}</div></div><div class="col-md-3"><label class="form-label" for="{{ $uid }}-finding_priority">{{ __('messages.findings.priority') }}</label><select id="{{ $uid }}-finding_priority" name="finding_priority" class="form-select">@foreach(\App\Models\Finding::PRIORITIES as $priority)<option value="{{ $priority }}" @selected((old('_native_test_modal') === $modalId ? old('finding_priority') : 'high')===$priority)>{{ __('messages.findings.priorities.'.$priority) }}</option>@endforeach</select><div class="form-text">{{ __('messages.native_tests.help.finding_priority') }}</div></div></div></div>
            </div>
            <div class="modal-footer aptoria-scrollable-form-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('messages.common.cancel') }}</button><button class="btn btn-primary"><i data-lucide="save" class="me-1"></i>{{ __('messages.native_tests.record_run') }}</button></div>
        </form>
    </div>
</div>
